### ISSUE TITLE
Grajenje URL-jev

### ISSUE THREAD

**Issue by jaanos** [MatejRojec/Gamma#1]
Svetujem, da za grajenje URL-jev (v predlogah in pri preusmeritvah) uporabite funkcijo `url`. Pri lokalnem poganjanju sicer ne bo nobene razlike, bodo pa tako povezave delovale pri poganjanju na Binderju. Za začetek bo tako treba namesto iz `bottle` uvažati iz `bottleext`:
```python
from bottleext import *
```

Funkciji `url` podaste ime funkcije, ki prikaže želeno stran (kot niz), nato pa po potrebi še ostale poimenovane parametre. Tako namesto
https://github.com/MatejRojec/Gamma/blob/77a75512b6ce490124e8b25f6e2e4597e2269347/gama.py#L102
naredite
```python
    redirect(url('uporabnik_get', id_uporabnika=id_uporabnika))
```
Podobno naredite tudi pri vseh povezavah v predlogah (tj., atributi `href`, `action`, `src`), npr.
```html
<form action="{{url('prijava')}}" method="post">
```

Mimogrede, da bo aplikacija tekla na Binderju, bo potrebno v `binder/start` popraviti ime glavnega programa:
```bash
export BOTTLE_RUNTIME=gama.py
```
Opažam še, da v glavnem programu uvažate knjižnico `requests`, ki je pa nikjer ne uporabite, tako da svetujem, da njen uvoz odstranite. Če pa jo boste vendarle potrebovali (oziroma katerokoli knjižnico, ki ni privzeto nameščena s Pythonom), pa jo dodajte še v `binder/requirements.txt` (obstoječi vrstici seveda pustita), da se bo ustrezno pripravilo okolje za poganjanje. Ko boste želeli, lahko potem v `README.md` dodaste še povezavo za poganjanje v Binderju:
```markdown
[![bottle.py](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/MatejRojec/Gamma/main?urlpath=proxy/8080/)
```

**Comment by MatejRojec** [comment]
Hvala za opombe, `requests` smo odstranili url-je smo pa naredili tako kot smo se menili na vajah.
Imamo še eno vprašanje glede `binder`-ja, ali moramo spremeniti oz. dodati še kaj za delovanje le-tega 
(poleg povezave z _javnost_ na bazo).
