### ISSUE TITLE
Skrivanje/odpiranje dela strani

### ISSUE THREAD

**Issue by jaanos** [MatejRojec/Gamma#2]
Če želite imeti del spletne strani, ki je prvotno zaprt, lahko uporabite značko `<details>`, npr.
```html
<details>
    <summary>Naslov</summary>
    <p>Zgornji naslov je vedno viden, ta vsebina pa je prvotno skrita.</p>
</details>
```
Če bi želeli, da je del že v začetku viden (pa ga lahko uporabnik po želji skrije), lahko začnete z `<details open>`.

**Comment by MatejRojec** [comment]
Hvala, smo dodali v kodo.
