### ISSUE TITLE
Binder

### ISSUE THREAD

**Issue by vitorozman** [MatejRojec/Gamma#4]
Imamo težave, ki se pojavijo samo na **Binder**-ju.

-  ne dela nam izris slike ozadja v:
https://github.com/MatejRojec/Gamma/blob/eae80d62db18009e779f35f141620b87dbdeb245/views/base.html#L55
 
- ko kliknemo na gumb **Odjava** uporabnik še zmeraj ostane prijavljen (lokano nimamo te težave)

Drugače smo s projektom zaključili, razen estetskih dodatkov, ki jih moramo dodati v  **Crypto**, **Borze** in **O podjetju** (Nameravamo jih narediti v roku parih dni, pred zagovorom).
Prosili bi za odobritev, za pristop k ustnem zagovoru.
Že v naprej se zahvaljujemo za pomoč.

**Comment by jaanos** [comment]
Kar se tiče prikaza slike, bo potrebno tudi tukaj narediti klic `bottle`ove funkcije `url` (ki je ločena od CSS-jeve funkcije `url`):
```css
background-image: url('{{url("static", filename="/img/bg1.png")}}');
```
Glede odjave je pa težava, da pri brisanju piškotka uporabite parameter `path='/'`, pri nastavljanju pa ne. Najlažje bo torej ta parameter odstraniti pri brisanju, lahko pa ga tudi dodaste pri nastavljanju piškotka `"id"` (torej pri prijavi in pri registraciji).

Sicer pa opažam, da v tabeli `devizni_tecaj` nimate glavnega ključa - smiselno bi ga seveda bilo imeti na stolpcih `osnovna_valuta`, `kotirajoca_valuta` in `datum razmerja`. Predlagal bi še, da v tabeli `uporabnik` na stolpec `email` dodaste še določilo `UNIQUE` (saj ga uporabljate kot uporabniško ime in nočete, da bi se vam vrednosti ponavljale). Prav tako bi bilo smiselno imeti še eno tabelo z valutami (lahko samo en stolpec), pa so potem ustrezni stolpci v tabelah `devizni_tecaj` in `transakcija` reference nanjo.

Vidim še, da ID-je transakcij in uporabnikov določate tako, da najprej pridobite največji obstoječi ID, nato pa izračunate ID za vstavljeno vrstico. Tak način ni najboljši, saj bi se lahko zgodilo, da se med pridobivanjem največjega ID-ja in vstavljanjem nove vrstice v tabelo že doda nova vrstica (z istim ID-jem), zaradi česar bi bilo vstavljanje neuspešno. Namesto tega bo bolje, če ustrezna stolpca naredite s tipom `SERIAL` in pustite bazi, da sama določi ID-je. Tako določeni ID lahko potem pridobite pri vstavljanju, npr.
```python
        cur.execute("""
            INSERT INTO uporabnik (ime, priimek, spol, datum_rojstva, drzava, email, geslo) 
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            RETURNING id_uporabnika
        """,
        [ime, priimek, spol, datum_rojstva, drzava, email, zgostitev])
        id_uporabnika, = cur.fetchone()
```

Še to: metoda `request.forms.get` ima težave s kodiranjem znakov. Da se izognete težavam, namesto npr. `request.forms.get('ime')` uporabite `request.forms.ime`. Svetujem tudi, da se pri neuspešni registraciji obrazec izpolni s predhodno vpisanimi podatki (glede na to, da naredite preusmeritev, lahko za to poskrbite s piškotki - lahko pa bi kar takoj prikazali obrazec in mu podali ustrezne podatke za izpolnitev).

Razen tega aplikacija izgleda v redu, tako da se lahko z @alenFMF domenite za termin zagovora. Ko boste imeli pripravljeno končno različico, mi sporočite, da dodam povezavo na repozitorij predmeta.

**Comment by rokrozman** [comment]
Pri ustvarjanju novih tabel s SERIAL in PRIMARY KEY-ji (ko pozenemo `gama.sql`) nam poizvedba ne deluje. 
Dodali smo tudi url pot za ozadje, vendar nam VSCode obarva vneseno kodo, kot napacno, ceprav nam nastavitev ozadja deluje. Ali to samo ignoriramo ali obstaja kaksna druga moznost?

**Comment by vitorozman** [comment]
Smo popravili tabele in nam trenutno app dela (tudi na **Binder**-ju). Zanima nas še kako si zapomnimo podatke uporabnika ob napačnem vnosu pri registraciji.

**Comment by jaanos** [comment]
Najprej bo treba v predlogi nastaviti vrednosti polj na ustrezne spremenljivke - tukaj sta primera za vnosno polje in izbirni gumb:
```html
<input type="text" name="ime" class="form-control" value="{{ime}}" ...>
<input type="radio" class="btn-check" name="spol" value="M" id="option1" {{'checked' if spol == 'M' else ''}}>
```
Seveda bo potrebno ustrezne spremenljivke podati pri klicu funkcije `template`:
```python
return template('registracija.html', naslov="Registracija", napaka=napaka, ime=ime, spol=spol, ...)
```
Ena možnost bi bila, da to naredite kar takoj, ko pride do napake (tj., brez preusmeritve in hranjenja napake v piškotek) - tedaj bo potrebno bodisi vse te spremenljivke nastaviti na privzete vrednosti v `registracija_get`, ali pa v sami predlogi s `setdefault`. Druga možnost je, da ohranite preusmeritev in vrednosti shranite v piškotke (podobno kot z napako). Tedaj si lahko pomagate s sledečima funkcijama:
```python
def nastaviPiskotek(piskotek, vrednost):
    response.set_cookie(piskotek, vrednost, path="/", secret=skrivnost)

def preberiPiskotek(piskotek, privzeto=''):
    vrednost = request.get_cookie(piskotek, default=privzeto, secret=skrivnost)
    response.delete_cookie(piskotek, path="/")
    return vrednost
```
Potem lahko ob napaki nastavite piškotke in naredite preusmeritev:
```python
while True:
    if email is None:
        nastaviSporocilo('Registracija ni možna ta email je že v uporabi')
    elif len(geslo) < 4:
        nastaviSporocilo('Geslo mora imeti vsaj 4 znake.')
    elif geslo != geslo2:
        nastaviSporocilo('Gesli se ne ujemata.')
    else: # ni napake, skočimo iz zanke
        break
    # imamo napako, nastavimo piškotke in preusmerimo
    nastaviPiskotek('ime', ime)
    nastaviPiskotek('spol', spol)
    ...
    redirect(url('registracija_get')) # sproži izjemo, zanka se torej konča
```

Pri prikazu obrazca potem vrednosti pridobite iz piškotkov:
```python
@get('/registracija')
def registracija_get():
    napaka = nastaviSporocilo()
    ime = preberiPiskotek('ime')
    spol = preberiPiskotek('spol', 'M')
    ....
    return template('registracija.html', naslov="Registracija", napaka=napaka, ime=ime, spol=spol, ...)
```

**Comment by vitorozman** [comment]
Hvala za poslano, smo dodali in zadeva dela.
S projektom smo zaključili tako da lahko dodate povezavo.

**Comment by jaanos** [comment]
V redu, bom dodal povezavo do projekta na repozitorij predmeta. Če se še niste, se lahko z @alenFMF domenite za termin zagovora. Če boste do takrat še kaj spreminjali, mi javite, da posodobim povezavo.
